### ISSUE TITLE
Problems when creating multiple peers 

### ISSUE THREAD

**Issue by xqly-stack** [fictivekin/wireguard#13]
Hi, I'm currently working on a school project to add new peers on sign-up.
Right now im just overwriting my previous peer.

The source code:
![image](https://user-images.githubusercontent.com/112006489/222966986-198657b3-d588-458d-87ce-cd9dce0c2553.png)

The webserver prompts you to create a user: 
![image](https://user-images.githubusercontent.com/112006489/222966849-cfdc18c1-7776-4ee0-bfce-11c6a522c745.png)

After the signup process, the webserver will then write the peer to the default wireguard server location.
When creating multiple accounts, the wg0-peers.conf-file gets overwritten with the most recent user. 
Is there any quick workaround to append the most recent peer, instead of overwriting the previous one?

My Project:
https://github.com/Projekt12-4/Login-System-VPN

**Comment by jnhmcknight** [comment]
There are 2 aspects that you should probably look at in order to resolve this problem:

1. In your [`/sign-up` view](https://github.com/Projekt12-4/Login-System-VPN/blob/a97a3d7acad51ccb2c59e3ad5dea6465bfab6a06/website/auth.py#L83), the server object is being instantiated cleanly on every signup request. If the server were created once in the app's startup, then the peers added in each signup request would persist in the server's configuration and be included in the rewriting of the server config. This would work correctly until the app is restarted, at which point all previously configured peers would disappear.
2. However, since the app is using a DB for the [users](https://github.com/Projekt12-4/Login-System-VPN/blob/a97a3d7acad51ccb2c59e3ad5dea6465bfab6a06/website/models.py), you could also have a model for the peers, to store them between app restarts. This would require that you load any existing peers into the server configuration at app startup, but you would then have peer persistence.

One security point to also consider, which may be outside of the project's requirements, is allowing the web server user to write to what are typically `root`-only files. There are ways to appropriately secure that setup, but it's usually safer to have another process read the saved configuration from the database and write the files.

**Comment by xqly-stack** [comment]
Thank you!
