### ISSUE TITLE
How to instantiate server from existing wg0.conf file

### ISSUE THREAD

**Issue by pclass-sensonix** [fictivekin/wireguard#6]
Thanks for this package, it is working great for me. One thing I don't see how to do is instantiate a Server object from an existing configuration. I am building a webserver that I can interact with to create new wireguard connections. The problem is that each time I start this webserver, it creates a new 'Server' object with a new set of public/private keys and so I need to re-create each of my clients. I am trying to figure out how to get the package to use my previous server configuration so that I can restart my application without re-creating all the clients.

Would you please help me understand how to do that? Thank you.

**Comment by jnhmcknight** [comment]
Unfortunately, at this time, there is no built-in way to read directly from WireGuard config files in this library. Feel free to submit a PR that has that functionality. It's on our list of things to add, but alas, we haven't gotten to it yet since we don't have need of that feature currently.

Our approach is more as follows, and it has been made easier by some of the more recent commits, which added functionality for getting a full JSON representation of a model's config. We store to the core configs to a database, and then on restart of any process (i.e.: your web service), we use the database records to reload into a `Server` or `Peer` model via keyword arguments.

```python

server = Server(
    'test-server',
    '192.168.75.1/24',
    private_key='ShmphOZy2kccMQdPOw+s0PbM3O5QkNIcxXMa60KA31s=',
    endpoint='wg-vpn.example.com',
    # other allowed keyword arguments
)

print(server.json(sort_keys=True, indent=4))

description = None
server_kwargs = {}
for key,val in server:
    if key == 'description':
        description = val
        continue

    server_kwargs.update({key: val})

# save `server_kwargs` and `description` to a db table somewhere

# on service restart, load `server_kwargs` and `description from the db table and instantiate the object
server2 = Server(
    description,
    **server_kwargs
)

print(server2.json(sort_keys=True, indent=4))
```

Does that help at all?

**Comment by pclass-sensonix** [comment]
Thank you - this does help. I will take this approach.

**Comment by jnhmcknight** [comment]
In order to get the new JSON handling described above, you'll need to grab the latest version ([v0.3.0](https://github.com/fictivekin/wireguard/releases/tag/v0.3.0)) which was published last night.

**Comment by UrfinJuice11** [comment]
When trying to instantiate the second server instance with:
`server2 = Server(
    description,
    **server_kwargs
)
`
Get the following error:
```Traceback (most recent call last):
  File "/home/kali/wg/wg.py", line 55, in <module>
    server2 = Server(
  File "/usr/local/lib/python3.10/dist-packages/wireguard/server.py", line 102, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/wireguard/peer.py", line 183, in __init__
    self.peers.extend(peers)
  File "/usr/local/lib/python3.10/dist-packages/wireguard/utils/sets.py", line 47, in extend
    self.add(value)
  File "/usr/local/lib/python3.10/dist-packages/wireguard/utils/sets.py", line 33, in add
    super().add(self._coerce_value(value))
  File "/usr/local/lib/python3.10/dist-packages/wireguard/peer.py", line 39, in _coerce_value
    raise ValueError('Provided value must be an instance of Peer')
ValueError: Provided value must be an instance of Peer
```

The full code is:

```from wireguard import Server, Peer
from wireguard.service import Interface

NET = '10.10.0.0/16'
ADDRESS = '10.10.0.1'
PUBLIC = 'edited'
PRIVATE = 'edited'
ENDPOINT = '172.20.0.6'
PORT = 51820
IFACE = 'wg0'
PEER_FILENAME = 'wg0-peers.conf'

def is_up(iface):
    iface = Interface(iface)
    try:
        iface.show()
        return 1
    except:
        return 0

def create_server(net, address, public_key, private_key, endpoint, port):
    server = Server('wapt-server', net, address=address, public_key=public_key, private_key=private_key, endpoint=endpoint, port=port)
    server.config().write()
    return server

def add_peer(name):
    server = create_server(NET, ADDRESS, PUBLIC, PRIVATE, ENDPOINT, PORT)
    server.config().write()
    peer = server.peer(name)
    public_key = peer.config().public_key.split('=')[1].strip()
    private_key = peer.config().private_key.split('=')[1].strip()
    peer_config = peer.config().local_config
    server.config().write()
    if is_up(IFACE):
        server.service.restart()
    else:
        server.service.start()
    return public_key, private_key, peer_config, server 


a,b,c,server = add_peer('testuser')

description = None
server_kwargs = {}
for key,val in server:
    if key == 'description':
        description = val
        continue
    server_kwargs.update({key: val})

server2 = Server(
    description,
    **server_kwargs
)
```

**Comment by jnhmcknight** [comment]
It would seem that we never tested for this exact scenario. Passing a `list` of `Peer` objects would work, but passing a `list` of `dict` does not. You would need to loop through the `peers` data from `server_kwargs`, transform each `dict` of peer data to a `Peer` object, and then set `server_kwargs['peer']` to the `list` of `Peer` objects.

Having that capability built-in natively, would probably be useful to include. I've added an issue for it, #10. Feel free to take a stab at adding that functionality. We welcome contributions, even if there haven't been many thus far.

**Comment by UrfinJuice11** [comment]
The whole problem is about that I can not run the server instance with current working server config and existing peers in wg0-peers.conf. So the FeatureRequest would be to create server instance from existin wg0.conf and wg0-peers.conf

**Comment by jnhmcknight** [comment]
> So the FeatureRequest would be to create server instance from existin wg0.conf and wg0-peers.conf

We'd welcome that enhancement too 😉

The biggest difficulty with that feature is that the Wireguard config files are not conformant to the INI spec, in that they have multiple `[peer]` sections, which is not technically allowed, as well as possibly duplicate keys in a section (ie: `PostUp` and `PostDown`) that aren't allowed in the standard either, and thus most INI parsers will fail to load the data correctly. Additionally, there is the possibility (ie: `PostUp = wg addconf wg0-peers.conf`) for included files that would need to be parsed automatically when the directive exists so that you're getting the full config, and not just a portion of it.

You could try https://pypi.org/project/wgconfig/ to read your configs, but the parsed config objects aren't directly usable with our `wireguard` package, and when last we tried the `wgconfig` package, it didn't handle included files automatically. Maybe the end solution is to make some sort of bridge between what `wgconfig` is parsing and how `wireguard` wants the data for manipulation.

**Comment by UrfinJuice11** [comment]
> It would seem that we never tested for this exact scenario. Passing a `list` of `Peer` objects would work, but passing a `list` of `dict` does not. You would need to loop through the `peers` data from `server_kwargs`, transform each `dict` of peer data to a `Peer` object, and then set `server_kwargs['peer']` to the `list` of `Peer` objects.
> 
> Having that capability built-in natively, would probably be useful to include. I've added an issue for it, #10. Feel free to take a stab at adding that functionality. We welcome contributions, even if there haven't been many thus far.

That workaround worked for me. Now use pickle for saving the current config to a temp file.
